// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOyIXYna2lMRmTDvqZ7xrZzAj6NMMaoNo',
    appId: '1:563657825817:web:f3853136e673ccf0de1488',
    messagingSenderId: '563657825817',
    projectId: 'suyatra-8ab36',
    authDomain: 'suyatra-8ab36.firebaseapp.com',
    storageBucket: 'suyatra-8ab36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0GXBX_g55htAW7b7_79uaqLPiXl9uwJs',
    appId: '1:563657825817:android:c2a97cac7a3db9f5de1488',
    messagingSenderId: '563657825817',
    projectId: 'suyatra-8ab36',
    storageBucket: 'suyatra-8ab36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2kQrDJh1mwS_PUxR22huLG9sB6jooJuE',
    appId: '1:563657825817:ios:4de780e84561a929de1488',
    messagingSenderId: '563657825817',
    projectId: 'suyatra-8ab36',
    storageBucket: 'suyatra-8ab36.appspot.com',
    iosBundleId: 'com.finnove.suyatra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2kQrDJh1mwS_PUxR22huLG9sB6jooJuE',
    appId: '1:563657825817:ios:cf03f5288d5600e0de1488',
    messagingSenderId: '563657825817',
    projectId: 'suyatra-8ab36',
    storageBucket: 'suyatra-8ab36.appspot.com',
    iosBundleId: 'com.finnove.suyatra.RunnerTests',
  );
}
