name: suyatra
description: "A new Flutter project."

publish_to: 'none'

version: 1.5.6+17

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  flutter_svg: ^2.0.9
  get_it: ^7.6.7
  http: ^1.2.0
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_html: ^3.0.0-beta.2
  share_plus: ^7.1.0
  firebase_core: ^2.25.3
  firebase_auth: ^4.17.3
  fluttertoast: ^8.2.4
  cloud_firestore: ^4.15.3
  webview_flutter: ^4.5.0
  shimmer: ^3.0.0
  scrollable_positioned_list: ^0.3.8
  google_sign_in: ^6.2.1
  url_launcher: ^6.2.4
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  otp_text_field: ^1.1.3
  package_info: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/categories/

  fonts:
    - family: InstrumentSans
      fonts:
        - asset: assets/fonts/InstrumentSans/InstrumentSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/InstrumentSans/InstrumentSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/InstrumentSans/InstrumentSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/InstrumentSans/InstrumentSans-Bold.ttf
          weight: 700